# pubspec.yaml
name: chronoplan_app
description: Your personal scheduler, alarm, and task manager.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shared_preferences: ^2.3.1
  intl: ^0.18.1
  url_launcher: ^6.2.6
  provider: ^6.0.5
  firebase_core: ^2.28.0 # For Firebase initialization
  firebase_auth: ^4.18.0  # For user authentication
  firebase_analytics: ^10.10.0 # For tracking user behavior
  firebase_crashlytics: ^3.5.0 # For crash reporting

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.4 # For mocking dependencies in tests
  build_runner: ^2.4.9 # For running code generators (like mockito's)

flutter:
  uses-material-design: true